//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/04 - 17:53:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="alergiasinmunizaciones"/> and <see cref="alergiasinmunizacionesDto"/>.
    /// </summary>
    public static partial class alergiasinmunizacionesAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="alergiasinmunizacionesDto"/> converted from <see cref="alergiasinmunizaciones"/>.</param>
        static partial void OnDTO(this alergiasinmunizaciones entity, alergiasinmunizacionesDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="alergiasinmunizaciones"/> converted from <see cref="alergiasinmunizacionesDto"/>.</param>
        static partial void OnEntity(this alergiasinmunizacionesDto dto, alergiasinmunizaciones entity);

        /// <summary>
        /// Converts this instance of <see cref="alergiasinmunizacionesDto"/> to an instance of <see cref="alergiasinmunizaciones"/>.
        /// </summary>
        /// <param name="dto"><see cref="alergiasinmunizacionesDto"/> to convert.</param>
        public static alergiasinmunizaciones ToEntity(this alergiasinmunizacionesDto dto)
        {
            if (dto == null) return null;

            var entity = new alergiasinmunizaciones();

            entity.v_AntecedentesId = dto.v_AntecedentesId;
            entity.v_PersonaId = dto.v_PersonaId;
            entity.b_Alergias = dto.b_Alergias;
            entity.i_Ninfluenza = dto.i_Ninfluenza;
            entity.i_NHepatitis = dto.i_NHepatitis;
            entity.i_Ntetano = dto.i_Ntetano;
            entity.i_NFiebreAmarilla = dto.i_NFiebreAmarilla;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="alergiasinmunizaciones"/> to an instance of <see cref="alergiasinmunizacionesDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="alergiasinmunizaciones"/> to convert.</param>
        public static alergiasinmunizacionesDto ToDTO(this alergiasinmunizaciones entity)
        {
            if (entity == null) return null;

            var dto = new alergiasinmunizacionesDto();

            dto.v_AntecedentesId = entity.v_AntecedentesId;
            dto.v_PersonaId = entity.v_PersonaId;
            dto.b_Alergias = entity.b_Alergias;
            dto.i_Ninfluenza = entity.i_Ninfluenza;
            dto.i_NHepatitis = entity.i_NHepatitis;
            dto.i_Ntetano = entity.i_Ntetano;
            dto.i_NFiebreAmarilla = entity.i_NFiebreAmarilla;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="alergiasinmunizacionesDto"/> to an instance of <see cref="alergiasinmunizaciones"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<alergiasinmunizaciones> ToEntities(this IEnumerable<alergiasinmunizacionesDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="alergiasinmunizaciones"/> to an instance of <see cref="alergiasinmunizacionesDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<alergiasinmunizacionesDto> ToDTOs(this IEnumerable<alergiasinmunizaciones> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
