//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/06 - 17:19:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="antecedentes"/> and <see cref="antecedentesDto"/>.
    /// </summary>
    public static partial class antecedentesAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="antecedentesDto"/> converted from <see cref="antecedentes"/>.</param>
        static partial void OnDTO(this antecedentes entity, antecedentesDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="antecedentes"/> converted from <see cref="antecedentesDto"/>.</param>
        static partial void OnEntity(this antecedentesDto dto, antecedentes entity);

        /// <summary>
        /// Converts this instance of <see cref="antecedentesDto"/> to an instance of <see cref="antecedentes"/>.
        /// </summary>
        /// <param name="dto"><see cref="antecedentesDto"/> to convert.</param>
        public static antecedentes ToEntity(this antecedentesDto dto)
        {
            if (dto == null) return null;

            var entity = new antecedentes();

            entity.v_AntecedentesId = dto.v_AntecedentesId;
            entity.v_PersonaId = dto.v_PersonaId;
            entity.v_AntPersonales = dto.v_AntPersonales;
            entity.v_AntFamiliares = dto.v_AntFamiliares;
            entity.v_AntLaborales = dto.v_AntLaborales;
            entity.v_AntPatologicos = dto.v_AntPatologicos;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="antecedentes"/> to an instance of <see cref="antecedentesDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="antecedentes"/> to convert.</param>
        public static antecedentesDto ToDTO(this antecedentes entity)
        {
            if (entity == null) return null;

            var dto = new antecedentesDto();

            dto.v_AntecedentesId = entity.v_AntecedentesId;
            dto.v_PersonaId = entity.v_PersonaId;
            dto.v_AntPersonales = entity.v_AntPersonales;
            dto.v_AntFamiliares = entity.v_AntFamiliares;
            dto.v_AntLaborales = entity.v_AntLaborales;
            dto.v_AntPatologicos = entity.v_AntPatologicos;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="antecedentesDto"/> to an instance of <see cref="antecedentes"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<antecedentes> ToEntities(this IEnumerable<antecedentesDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="antecedentes"/> to an instance of <see cref="antecedentesDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<antecedentesDto> ToDTOs(this IEnumerable<antecedentes> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
