//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/06 - 17:19:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="audiometria"/> and <see cref="audiometriaDto"/>.
    /// </summary>
    public static partial class audiometriaAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="audiometriaDto"/> converted from <see cref="audiometria"/>.</param>
        static partial void OnDTO(this audiometria entity, audiometriaDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="audiometria"/> converted from <see cref="audiometriaDto"/>.</param>
        static partial void OnEntity(this audiometriaDto dto, audiometria entity);

        /// <summary>
        /// Converts this instance of <see cref="audiometriaDto"/> to an instance of <see cref="audiometria"/>.
        /// </summary>
        /// <param name="dto"><see cref="audiometriaDto"/> to convert.</param>
        public static audiometria ToEntity(this audiometriaDto dto)
        {
            if (dto == null) return null;

            var entity = new audiometria();

            entity.v_AudiometriaId = dto.v_AudiometriaId;
            entity.v_ServicioId = dto.v_ServicioId;
            entity.v_Calibracion = dto.v_Calibracion;
            entity.v_OtoscopiaOD = dto.v_OtoscopiaOD;
            entity.v_OtoscopiaOI = dto.v_OtoscopiaOI;
            entity.v_VAOD125 = dto.v_VAOD125;
            entity.v_VAOD250 = dto.v_VAOD250;
            entity.v_VAOD500 = dto.v_VAOD500;
            entity.v_VAOD1000 = dto.v_VAOD1000;
            entity.v_VAOD2000 = dto.v_VAOD2000;
            entity.v_VAOD3000 = dto.v_VAOD3000;
            entity.v_VAOD4000 = dto.v_VAOD4000;
            entity.v_VAOD6000 = dto.v_VAOD6000;
            entity.v_VAOD8000 = dto.v_VAOD8000;
            entity.v_VAOI125 = dto.v_VAOI125;
            entity.v_VAOI250 = dto.v_VAOI250;
            entity.v_VAOI500 = dto.v_VAOI500;
            entity.v_VAOI1000 = dto.v_VAOI1000;
            entity.v_VAOI2000 = dto.v_VAOI2000;
            entity.v_VAOI3000 = dto.v_VAOI3000;
            entity.v_VAOI4000 = dto.v_VAOI4000;
            entity.v_VAOI6000 = dto.v_VAOI6000;
            entity.v_VAOI8000 = dto.v_VAOI8000;
            entity.v_VOOD125 = dto.v_VOOD125;
            entity.v_VOOD250 = dto.v_VOOD250;
            entity.v_VOOD500 = dto.v_VOOD500;
            entity.v_VOOD1000 = dto.v_VOOD1000;
            entity.v_VOOD2000 = dto.v_VOOD2000;
            entity.v_VOOD3000 = dto.v_VOOD3000;
            entity.v_VOOD4000 = dto.v_VOOD4000;
            entity.v_VOOD6000 = dto.v_VOOD6000;
            entity.v_VOOD8000 = dto.v_VOOD8000;
            entity.v_VOOI125 = dto.v_VOOI125;
            entity.v_VOOI250 = dto.v_VOOI250;
            entity.v_VOOI500 = dto.v_VOOI500;
            entity.v_VOOI1000 = dto.v_VOOI1000;
            entity.v_VOOI2000 = dto.v_VOOI2000;
            entity.v_VOOI3000 = dto.v_VOOI3000;
            entity.v_VOOI4000 = dto.v_VOOI4000;
            entity.v_VOOI6000 = dto.v_VOOI6000;
            entity.v_VOOI8000 = dto.v_VOOI8000;
            entity.v_EM_A_OD125 = dto.v_EM_A_OD125;
            entity.v_EM_A_OD250 = dto.v_EM_A_OD250;
            entity.v_EM_A_OD500 = dto.v_EM_A_OD500;
            entity.v_EM_A_OD1000 = dto.v_EM_A_OD1000;
            entity.v_EM_A_OD2000 = dto.v_EM_A_OD2000;
            entity.v_EM_A_OD3000 = dto.v_EM_A_OD3000;
            entity.v_EM_A_OD4000 = dto.v_EM_A_OD4000;
            entity.v_EM_A_OD6000 = dto.v_EM_A_OD6000;
            entity.v_EM_A_OD8000 = dto.v_EM_A_OD8000;
            entity.v_EM_A_OI125 = dto.v_EM_A_OI125;
            entity.v_EM_A_OI250 = dto.v_EM_A_OI250;
            entity.v_EM_A_OI500 = dto.v_EM_A_OI500;
            entity.v_EM_A_OI1000 = dto.v_EM_A_OI1000;
            entity.v_EM_A_OI2000 = dto.v_EM_A_OI2000;
            entity.v_EM_A_OI3000 = dto.v_EM_A_OI3000;
            entity.v_EM_A_OI_4000 = dto.v_EM_A_OI_4000;
            entity.v_EM_A_OI6000 = dto.v_EM_A_OI6000;
            entity.v_EM_A_OI8000 = dto.v_EM_A_OI8000;
            entity.v_EM_O_OD125 = dto.v_EM_O_OD125;
            entity.v_EM_O_OD250 = dto.v_EM_O_OD250;
            entity.v_EM_O_OD500 = dto.v_EM_O_OD500;
            entity.v_EM_O_OD1000 = dto.v_EM_O_OD1000;
            entity.v_EM_O_OD2000 = dto.v_EM_O_OD2000;
            entity.v_EM_O_OD3000 = dto.v_EM_O_OD3000;
            entity.v_EM_O_OD4000 = dto.v_EM_O_OD4000;
            entity.v_EM_O_OD6000 = dto.v_EM_O_OD6000;
            entity.v_EM_O_OD8000 = dto.v_EM_O_OD8000;
            entity.v_EM_O_OI125 = dto.v_EM_O_OI125;
            entity.v_EM_O_OI250 = dto.v_EM_O_OI250;
            entity.v_EM_O_OI500 = dto.v_EM_O_OI500;
            entity.v_EM_O_OI1000 = dto.v_EM_O_OI1000;
            entity.v_EM_O_OI2000 = dto.v_EM_O_OI2000;
            entity.v_EM_O_OI3000 = dto.v_EM_O_OI3000;
            entity.v_EM_O_OI4000 = dto.v_EM_O_OI4000;
            entity.v_EM_O_OI6000 = dto.v_EM_O_OI6000;
            entity.v_EM_O_OI8000 = dto.v_EM_O_OI8000;
            entity.v_ConclusionesAudiometria = dto.v_ConclusionesAudiometria;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="audiometria"/> to an instance of <see cref="audiometriaDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="audiometria"/> to convert.</param>
        public static audiometriaDto ToDTO(this audiometria entity)
        {
            if (entity == null) return null;

            var dto = new audiometriaDto();

            dto.v_AudiometriaId = entity.v_AudiometriaId;
            dto.v_ServicioId = entity.v_ServicioId;
            dto.v_Calibracion = entity.v_Calibracion;
            dto.v_OtoscopiaOD = entity.v_OtoscopiaOD;
            dto.v_OtoscopiaOI = entity.v_OtoscopiaOI;
            dto.v_VAOD125 = entity.v_VAOD125;
            dto.v_VAOD250 = entity.v_VAOD250;
            dto.v_VAOD500 = entity.v_VAOD500;
            dto.v_VAOD1000 = entity.v_VAOD1000;
            dto.v_VAOD2000 = entity.v_VAOD2000;
            dto.v_VAOD3000 = entity.v_VAOD3000;
            dto.v_VAOD4000 = entity.v_VAOD4000;
            dto.v_VAOD6000 = entity.v_VAOD6000;
            dto.v_VAOD8000 = entity.v_VAOD8000;
            dto.v_VAOI125 = entity.v_VAOI125;
            dto.v_VAOI250 = entity.v_VAOI250;
            dto.v_VAOI500 = entity.v_VAOI500;
            dto.v_VAOI1000 = entity.v_VAOI1000;
            dto.v_VAOI2000 = entity.v_VAOI2000;
            dto.v_VAOI3000 = entity.v_VAOI3000;
            dto.v_VAOI4000 = entity.v_VAOI4000;
            dto.v_VAOI6000 = entity.v_VAOI6000;
            dto.v_VAOI8000 = entity.v_VAOI8000;
            dto.v_VOOD125 = entity.v_VOOD125;
            dto.v_VOOD250 = entity.v_VOOD250;
            dto.v_VOOD500 = entity.v_VOOD500;
            dto.v_VOOD1000 = entity.v_VOOD1000;
            dto.v_VOOD2000 = entity.v_VOOD2000;
            dto.v_VOOD3000 = entity.v_VOOD3000;
            dto.v_VOOD4000 = entity.v_VOOD4000;
            dto.v_VOOD6000 = entity.v_VOOD6000;
            dto.v_VOOD8000 = entity.v_VOOD8000;
            dto.v_VOOI125 = entity.v_VOOI125;
            dto.v_VOOI250 = entity.v_VOOI250;
            dto.v_VOOI500 = entity.v_VOOI500;
            dto.v_VOOI1000 = entity.v_VOOI1000;
            dto.v_VOOI2000 = entity.v_VOOI2000;
            dto.v_VOOI3000 = entity.v_VOOI3000;
            dto.v_VOOI4000 = entity.v_VOOI4000;
            dto.v_VOOI6000 = entity.v_VOOI6000;
            dto.v_VOOI8000 = entity.v_VOOI8000;
            dto.v_EM_A_OD125 = entity.v_EM_A_OD125;
            dto.v_EM_A_OD250 = entity.v_EM_A_OD250;
            dto.v_EM_A_OD500 = entity.v_EM_A_OD500;
            dto.v_EM_A_OD1000 = entity.v_EM_A_OD1000;
            dto.v_EM_A_OD2000 = entity.v_EM_A_OD2000;
            dto.v_EM_A_OD3000 = entity.v_EM_A_OD3000;
            dto.v_EM_A_OD4000 = entity.v_EM_A_OD4000;
            dto.v_EM_A_OD6000 = entity.v_EM_A_OD6000;
            dto.v_EM_A_OD8000 = entity.v_EM_A_OD8000;
            dto.v_EM_A_OI125 = entity.v_EM_A_OI125;
            dto.v_EM_A_OI250 = entity.v_EM_A_OI250;
            dto.v_EM_A_OI500 = entity.v_EM_A_OI500;
            dto.v_EM_A_OI1000 = entity.v_EM_A_OI1000;
            dto.v_EM_A_OI2000 = entity.v_EM_A_OI2000;
            dto.v_EM_A_OI3000 = entity.v_EM_A_OI3000;
            dto.v_EM_A_OI_4000 = entity.v_EM_A_OI_4000;
            dto.v_EM_A_OI6000 = entity.v_EM_A_OI6000;
            dto.v_EM_A_OI8000 = entity.v_EM_A_OI8000;
            dto.v_EM_O_OD125 = entity.v_EM_O_OD125;
            dto.v_EM_O_OD250 = entity.v_EM_O_OD250;
            dto.v_EM_O_OD500 = entity.v_EM_O_OD500;
            dto.v_EM_O_OD1000 = entity.v_EM_O_OD1000;
            dto.v_EM_O_OD2000 = entity.v_EM_O_OD2000;
            dto.v_EM_O_OD3000 = entity.v_EM_O_OD3000;
            dto.v_EM_O_OD4000 = entity.v_EM_O_OD4000;
            dto.v_EM_O_OD6000 = entity.v_EM_O_OD6000;
            dto.v_EM_O_OD8000 = entity.v_EM_O_OD8000;
            dto.v_EM_O_OI125 = entity.v_EM_O_OI125;
            dto.v_EM_O_OI250 = entity.v_EM_O_OI250;
            dto.v_EM_O_OI500 = entity.v_EM_O_OI500;
            dto.v_EM_O_OI1000 = entity.v_EM_O_OI1000;
            dto.v_EM_O_OI2000 = entity.v_EM_O_OI2000;
            dto.v_EM_O_OI3000 = entity.v_EM_O_OI3000;
            dto.v_EM_O_OI4000 = entity.v_EM_O_OI4000;
            dto.v_EM_O_OI6000 = entity.v_EM_O_OI6000;
            dto.v_EM_O_OI8000 = entity.v_EM_O_OI8000;
            dto.v_ConclusionesAudiometria = entity.v_ConclusionesAudiometria;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="audiometriaDto"/> to an instance of <see cref="audiometria"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<audiometria> ToEntities(this IEnumerable<audiometriaDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="audiometria"/> to an instance of <see cref="audiometriaDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<audiometriaDto> ToDTOs(this IEnumerable<audiometria> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
