//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/06 - 17:20:42
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="espirometria"/> and <see cref="espirometriaDto"/>.
    /// </summary>
    public static partial class espirometriaAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="espirometriaDto"/> converted from <see cref="espirometria"/>.</param>
        static partial void OnDTO(this espirometria entity, espirometriaDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="espirometria"/> converted from <see cref="espirometriaDto"/>.</param>
        static partial void OnEntity(this espirometriaDto dto, espirometria entity);

        /// <summary>
        /// Converts this instance of <see cref="espirometriaDto"/> to an instance of <see cref="espirometria"/>.
        /// </summary>
        /// <param name="dto"><see cref="espirometriaDto"/> to convert.</param>
        public static espirometria ToEntity(this espirometriaDto dto)
        {
            if (dto == null) return null;

            var entity = new espirometria();

            entity.v_EspirometriaId = dto.v_EspirometriaId;
            entity.v_ServicioId = dto.v_ServicioId;
            entity.v_FVC = dto.v_FVC;
            entity.v_VEF1 = dto.v_VEF1;
            entity.v_VEFCVF = dto.v_VEFCVF;
            entity.v_ConclusionesEspirometria = dto.v_ConclusionesEspirometria;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="espirometria"/> to an instance of <see cref="espirometriaDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="espirometria"/> to convert.</param>
        public static espirometriaDto ToDTO(this espirometria entity)
        {
            if (entity == null) return null;

            var dto = new espirometriaDto();

            dto.v_EspirometriaId = entity.v_EspirometriaId;
            dto.v_ServicioId = entity.v_ServicioId;
            dto.v_FVC = entity.v_FVC;
            dto.v_VEF1 = entity.v_VEF1;
            dto.v_VEFCVF = entity.v_VEFCVF;
            dto.v_ConclusionesEspirometria = entity.v_ConclusionesEspirometria;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="espirometriaDto"/> to an instance of <see cref="espirometria"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<espirometria> ToEntities(this IEnumerable<espirometriaDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="espirometria"/> to an instance of <see cref="espirometriaDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<espirometriaDto> ToDTOs(this IEnumerable<espirometria> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
