//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/04 - 17:54:45
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="habitos"/> and <see cref="habitosDto"/>.
    /// </summary>
    public static partial class habitosAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="habitosDto"/> converted from <see cref="habitos"/>.</param>
        static partial void OnDTO(this habitos entity, habitosDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="habitos"/> converted from <see cref="habitosDto"/>.</param>
        static partial void OnEntity(this habitosDto dto, habitos entity);

        /// <summary>
        /// Converts this instance of <see cref="habitosDto"/> to an instance of <see cref="habitos"/>.
        /// </summary>
        /// <param name="dto"><see cref="habitosDto"/> to convert.</param>
        public static habitos ToEntity(this habitosDto dto)
        {
            if (dto == null) return null;

            var entity = new habitos();

            entity.v_AntecedentesId = dto.v_AntecedentesId;
            entity.v_PersonaId = dto.v_PersonaId;
            entity.v_HabNocAlcohol = dto.v_HabNocAlcohol;
            entity.v_HabNocTabaco = dto.v_HabNocTabaco;
            entity.v_HabNocDrogas = dto.v_HabNocDrogas;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="habitos"/> to an instance of <see cref="habitosDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="habitos"/> to convert.</param>
        public static habitosDto ToDTO(this habitos entity)
        {
            if (entity == null) return null;

            var dto = new habitosDto();

            dto.v_AntecedentesId = entity.v_AntecedentesId;
            dto.v_PersonaId = entity.v_PersonaId;
            dto.v_HabNocAlcohol = entity.v_HabNocAlcohol;
            dto.v_HabNocTabaco = entity.v_HabNocTabaco;
            dto.v_HabNocDrogas = entity.v_HabNocDrogas;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="habitosDto"/> to an instance of <see cref="habitos"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<habitos> ToEntities(this IEnumerable<habitosDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="habitos"/> to an instance of <see cref="habitosDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<habitosDto> ToDTOs(this IEnumerable<habitos> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
