//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/04 - 17:55:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="laboratorio"/> and <see cref="laboratorioDto"/>.
    /// </summary>
    public static partial class laboratorioAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="laboratorioDto"/> converted from <see cref="laboratorio"/>.</param>
        static partial void OnDTO(this laboratorio entity, laboratorioDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="laboratorio"/> converted from <see cref="laboratorioDto"/>.</param>
        static partial void OnEntity(this laboratorioDto dto, laboratorio entity);

        /// <summary>
        /// Converts this instance of <see cref="laboratorioDto"/> to an instance of <see cref="laboratorio"/>.
        /// </summary>
        /// <param name="dto"><see cref="laboratorioDto"/> to convert.</param>
        public static laboratorio ToEntity(this laboratorioDto dto)
        {
            if (dto == null) return null;

            var entity = new laboratorio();

            entity.v_LaboratorioId = dto.v_LaboratorioId;
            entity.v_ServicioId = dto.v_ServicioId;
            entity.v_Hemoglobina = dto.v_Hemoglobina;
            entity.v_Hematocrito = dto.v_Hematocrito;
            entity.v_NeutrofilosSegementados = dto.v_NeutrofilosSegementados;
            entity.v_Abastonados = dto.v_Abastonados;
            entity.v_Segmentados = dto.v_Segmentados;
            entity.v_Monocitos = dto.v_Monocitos;
            entity.v_Eosinofilos = dto.v_Eosinofilos;
            entity.v_Basofilos = dto.v_Basofilos;
            entity.v_Linfocitos = dto.v_Linfocitos;
            entity.v_Hematies = dto.v_Hematies;
            entity.v_Plaquetas = dto.v_Plaquetas;
            entity.v_Mielocitos = dto.v_Mielocitos;
            entity.v_Juveniles = dto.v_Juveniles;
            entity.v_Glucosa = dto.v_Glucosa;
            entity.v_ColesterolTotal = dto.v_ColesterolTotal;
            entity.v_ColesterolHDL = dto.v_ColesterolHDL;
            entity.v_ColesterolLDL = dto.v_ColesterolLDL;
            entity.v_VLDL = dto.v_VLDL;
            entity.v_Trigliceridos = dto.v_Trigliceridos;
            entity.v_TGO = dto.v_TGO;
            entity.v_TGP = dto.v_TGP;
            entity.v_CreatininaSuero = dto.v_CreatininaSuero;
            entity.v_Color = dto.v_Color;
            entity.v_Aspecto = dto.v_Aspecto;
            entity.v_Densidad = dto.v_Densidad;
            entity.v_ReaccionPH = dto.v_ReaccionPH;
            entity.v_GlucosaExamenCompletoOrina = dto.v_GlucosaExamenCompletoOrina;
            entity.v_Bilirrubinas = dto.v_Bilirrubinas;
            entity.v_Cetonas = dto.v_Cetonas;
            entity.v_ProteinasTotales = dto.v_ProteinasTotales;
            entity.v_Urobilinogeno = dto.v_Urobilinogeno;
            entity.v_Leucocitos = dto.v_Leucocitos;
            entity.v_Hematies_ = dto.v_Hematies_;
            entity.v_Levaduras = dto.v_Levaduras;
            entity.v_CristDeoxalatosCalcio = dto.v_CristDeoxalatosCalcio;
            entity.v_Germenes = dto.v_Germenes;
            entity.v_Albumina = dto.v_Albumina;
            entity.v_LeucocitosTotales = dto.v_LeucocitosTotales;
            entity.v_Piocitos = dto.v_Piocitos;
            entity.v_FilamentosMucoides = dto.v_FilamentosMucoides;
            entity.v_CCVolumenCorpuscularMedio = dto.v_CCVolumenCorpuscularMedio;
            entity.v_CCHBCorpuscular = dto.v_CCHBCorpuscular;
            entity.v_LuesVDRL = dto.v_LuesVDRL;
            entity.v_PlomoSangre = dto.v_PlomoSangre;
            entity.v_Magnesio = dto.v_Magnesio;
            entity.v_Cocaina = dto.v_Cocaina;
            entity.v_Marihuana = dto.v_Marihuana;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="laboratorio"/> to an instance of <see cref="laboratorioDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="laboratorio"/> to convert.</param>
        public static laboratorioDto ToDTO(this laboratorio entity)
        {
            if (entity == null) return null;

            var dto = new laboratorioDto();

            dto.v_LaboratorioId = entity.v_LaboratorioId;
            dto.v_ServicioId = entity.v_ServicioId;
            dto.v_Hemoglobina = entity.v_Hemoglobina;
            dto.v_Hematocrito = entity.v_Hematocrito;
            dto.v_NeutrofilosSegementados = entity.v_NeutrofilosSegementados;
            dto.v_Abastonados = entity.v_Abastonados;
            dto.v_Segmentados = entity.v_Segmentados;
            dto.v_Monocitos = entity.v_Monocitos;
            dto.v_Eosinofilos = entity.v_Eosinofilos;
            dto.v_Basofilos = entity.v_Basofilos;
            dto.v_Linfocitos = entity.v_Linfocitos;
            dto.v_Hematies = entity.v_Hematies;
            dto.v_Plaquetas = entity.v_Plaquetas;
            dto.v_Mielocitos = entity.v_Mielocitos;
            dto.v_Juveniles = entity.v_Juveniles;
            dto.v_Glucosa = entity.v_Glucosa;
            dto.v_ColesterolTotal = entity.v_ColesterolTotal;
            dto.v_ColesterolHDL = entity.v_ColesterolHDL;
            dto.v_ColesterolLDL = entity.v_ColesterolLDL;
            dto.v_VLDL = entity.v_VLDL;
            dto.v_Trigliceridos = entity.v_Trigliceridos;
            dto.v_TGO = entity.v_TGO;
            dto.v_TGP = entity.v_TGP;
            dto.v_CreatininaSuero = entity.v_CreatininaSuero;
            dto.v_Color = entity.v_Color;
            dto.v_Aspecto = entity.v_Aspecto;
            dto.v_Densidad = entity.v_Densidad;
            dto.v_ReaccionPH = entity.v_ReaccionPH;
            dto.v_GlucosaExamenCompletoOrina = entity.v_GlucosaExamenCompletoOrina;
            dto.v_Bilirrubinas = entity.v_Bilirrubinas;
            dto.v_Cetonas = entity.v_Cetonas;
            dto.v_ProteinasTotales = entity.v_ProteinasTotales;
            dto.v_Urobilinogeno = entity.v_Urobilinogeno;
            dto.v_Leucocitos = entity.v_Leucocitos;
            dto.v_Hematies_ = entity.v_Hematies_;
            dto.v_Levaduras = entity.v_Levaduras;
            dto.v_CristDeoxalatosCalcio = entity.v_CristDeoxalatosCalcio;
            dto.v_Germenes = entity.v_Germenes;
            dto.v_Albumina = entity.v_Albumina;
            dto.v_LeucocitosTotales = entity.v_LeucocitosTotales;
            dto.v_Piocitos = entity.v_Piocitos;
            dto.v_FilamentosMucoides = entity.v_FilamentosMucoides;
            dto.v_CCVolumenCorpuscularMedio = entity.v_CCVolumenCorpuscularMedio;
            dto.v_CCHBCorpuscular = entity.v_CCHBCorpuscular;
            dto.v_LuesVDRL = entity.v_LuesVDRL;
            dto.v_PlomoSangre = entity.v_PlomoSangre;
            dto.v_Magnesio = entity.v_Magnesio;
            dto.v_Cocaina = entity.v_Cocaina;
            dto.v_Marihuana = entity.v_Marihuana;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="laboratorioDto"/> to an instance of <see cref="laboratorio"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<laboratorio> ToEntities(this IEnumerable<laboratorioDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="laboratorio"/> to an instance of <see cref="laboratorioDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<laboratorioDto> ToDTOs(this IEnumerable<laboratorio> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
