//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/06 - 17:21:17
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="medicina"/> and <see cref="medicinaDto"/>.
    /// </summary>
    public static partial class medicinaAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="medicinaDto"/> converted from <see cref="medicina"/>.</param>
        static partial void OnDTO(this medicina entity, medicinaDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="medicina"/> converted from <see cref="medicinaDto"/>.</param>
        static partial void OnEntity(this medicinaDto dto, medicina entity);

        /// <summary>
        /// Converts this instance of <see cref="medicinaDto"/> to an instance of <see cref="medicina"/>.
        /// </summary>
        /// <param name="dto"><see cref="medicinaDto"/> to convert.</param>
        public static medicina ToEntity(this medicinaDto dto)
        {
            if (dto == null) return null;

            var entity = new medicina();

            entity.v_MedicinaId = dto.v_MedicinaId;
            entity.v_ServicioId = dto.v_ServicioId;
            entity.v_Cabeza = dto.v_Cabeza;
            entity.v_Cuello = dto.v_Cuello;
            entity.v_Nariz = dto.v_Nariz;
            entity.v_BocaAmigdalas = dto.v_BocaAmigdalas;
            entity.v_MiembrosSuperiores = dto.v_MiembrosSuperiores;
            entity.v_MiembrosInferiores = dto.v_MiembrosInferiores;
            entity.v_ReflejosOsteos = dto.v_ReflejosOsteos;
            entity.v_Columna = dto.v_Columna;
            entity.v_EnMarcha = dto.v_EnMarcha;
            entity.v_Abdomen = dto.v_Abdomen;
            entity.v_DesGeneral = dto.v_DesGeneral;
            entity.v_Anillos = dto.v_Anillos;
            entity.v_Hernias = dto.v_Hernias;
            entity.v_Varices = dto.v_Varices;
            entity.v_Genitales = dto.v_Genitales;
            entity.v_Ganglios = dto.v_Ganglios;
            entity.v_LenguajeAtencionMemoria = dto.v_LenguajeAtencionMemoria;
            entity.v_ConclusionesMedicina = dto.v_ConclusionesMedicina;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="medicina"/> to an instance of <see cref="medicinaDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="medicina"/> to convert.</param>
        public static medicinaDto ToDTO(this medicina entity)
        {
            if (entity == null) return null;

            var dto = new medicinaDto();

            dto.v_MedicinaId = entity.v_MedicinaId;
            dto.v_ServicioId = entity.v_ServicioId;
            dto.v_Cabeza = entity.v_Cabeza;
            dto.v_Cuello = entity.v_Cuello;
            dto.v_Nariz = entity.v_Nariz;
            dto.v_BocaAmigdalas = entity.v_BocaAmigdalas;
            dto.v_MiembrosSuperiores = entity.v_MiembrosSuperiores;
            dto.v_MiembrosInferiores = entity.v_MiembrosInferiores;
            dto.v_ReflejosOsteos = entity.v_ReflejosOsteos;
            dto.v_Columna = entity.v_Columna;
            dto.v_EnMarcha = entity.v_EnMarcha;
            dto.v_Abdomen = entity.v_Abdomen;
            dto.v_DesGeneral = entity.v_DesGeneral;
            dto.v_Anillos = entity.v_Anillos;
            dto.v_Hernias = entity.v_Hernias;
            dto.v_Varices = entity.v_Varices;
            dto.v_Genitales = entity.v_Genitales;
            dto.v_Ganglios = entity.v_Ganglios;
            dto.v_LenguajeAtencionMemoria = entity.v_LenguajeAtencionMemoria;
            dto.v_ConclusionesMedicina = entity.v_ConclusionesMedicina;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="medicinaDto"/> to an instance of <see cref="medicina"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<medicina> ToEntities(this IEnumerable<medicinaDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="medicina"/> to an instance of <see cref="medicinaDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<medicinaDto> ToDTOs(this IEnumerable<medicina> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
