//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.1 (entitiestodtos.codeplex.com).
//     Timestamp: 2024/12/06 - 17:21:48
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="odontologia"/> and <see cref="odontologiaDto"/>.
    /// </summary>
    public static partial class odontologiaAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="odontologiaDto"/> converted from <see cref="odontologia"/>.</param>
        static partial void OnDTO(this odontologia entity, odontologiaDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="odontologia"/> converted from <see cref="odontologiaDto"/>.</param>
        static partial void OnEntity(this odontologiaDto dto, odontologia entity);

        /// <summary>
        /// Converts this instance of <see cref="odontologiaDto"/> to an instance of <see cref="odontologia"/>.
        /// </summary>
        /// <param name="dto"><see cref="odontologiaDto"/> to convert.</param>
        public static odontologia ToEntity(this odontologiaDto dto)
        {
            if (dto == null) return null;

            var entity = new odontologia();

            entity.v_OdontologiaId = dto.v_OdontologiaId;
            entity.v_ServicioId = dto.v_ServicioId;
            entity.b_Gingivitis = dto.b_Gingivitis;
            entity.i_PiezasMalEstado = dto.i_PiezasMalEstado;
            entity.i_PiezasFaltan = dto.i_PiezasFaltan;
            entity.i_PiezasMalEstadoTriaje = dto.i_PiezasMalEstadoTriaje;
            entity.i_PiezasFaltanTriaje = dto.i_PiezasFaltanTriaje;
            entity.v_ConclusionesOdontologia = dto.v_ConclusionesOdontologia;
            entity.d_FechaInsercion = dto.d_FechaInsercion;
            entity.i_UsuarioInsertaId = dto.i_UsuarioInsertaId;
            entity.d_FechaActualizacion = dto.d_FechaActualizacion;
            entity.i_UsuarioActualizaId = dto.i_UsuarioActualizaId;
            entity.i_EsEliminado = dto.i_EsEliminado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="odontologia"/> to an instance of <see cref="odontologiaDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="odontologia"/> to convert.</param>
        public static odontologiaDto ToDTO(this odontologia entity)
        {
            if (entity == null) return null;

            var dto = new odontologiaDto();

            dto.v_OdontologiaId = entity.v_OdontologiaId;
            dto.v_ServicioId = entity.v_ServicioId;
            dto.b_Gingivitis = entity.b_Gingivitis;
            dto.i_PiezasMalEstado = entity.i_PiezasMalEstado;
            dto.i_PiezasFaltan = entity.i_PiezasFaltan;
            dto.i_PiezasMalEstadoTriaje = entity.i_PiezasMalEstadoTriaje;
            dto.i_PiezasFaltanTriaje = entity.i_PiezasFaltanTriaje;
            dto.v_ConclusionesOdontologia = entity.v_ConclusionesOdontologia;
            dto.d_FechaInsercion = entity.d_FechaInsercion;
            dto.i_UsuarioInsertaId = entity.i_UsuarioInsertaId;
            dto.d_FechaActualizacion = entity.d_FechaActualizacion;
            dto.i_UsuarioActualizaId = entity.i_UsuarioActualizaId;
            dto.i_EsEliminado = entity.i_EsEliminado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="odontologiaDto"/> to an instance of <see cref="odontologia"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<odontologia> ToEntities(this IEnumerable<odontologiaDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="odontologia"/> to an instance of <see cref="odontologiaDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<odontologiaDto> ToDTOs(this IEnumerable<odontologia> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
